//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Controls/TetrisControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TetrisControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TetrisControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TetrisControls"",
    ""maps"": [
        {
            ""name"": ""TetrisRight"",
            ""id"": ""c796d4f9-35ba-4814-86be-9054e05a2aa5"",
            ""actions"": [
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""1cd4406d-b23f-49e4-b4aa-b349474c8023"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f2f382e7-85a4-4fea-9a8c-4aed12c9409d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""23eeb5c1-aa76-40d7-b549-93c8e8d00295"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";XR;Generic XR Controller"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8412c2db-3ba4-4042-b757-9bceb04541a1"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";XR;Generic XR Controller"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""610a7aed-f70f-4ea5-bbf3-46961dc6d405"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8bcb8872-3564-4442-8e8d-df8783affdba"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""548ee92a-0e79-430c-8325-e07a75514430"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""TetrisLeft"",
            ""id"": ""dbdc36e8-1298-4af7-9064-094f71051954"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""e0714017-bd02-41cd-aa5b-b3b4fea9b16b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24664eb5-8399-4990-9896-7a2fbe645f92"",
                    ""path"": ""<XRController>{LeftHand}/{Primary2DAxis}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Generic XR Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9877aedf-1cd2-4ef3-b119-921a1baa65ea"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""66cab5b9-e7a7-4e01-9050-3138ec678a5a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""98a85bc7-ed39-4b04-9537-7c5ef981632f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3f8d97f4-8ff4-41a0-969c-74186568f5ed"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""03dc0d1c-f4fc-42c6-8f8a-b4766b3a54e5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TetrisRight
        m_TetrisRight = asset.FindActionMap("TetrisRight", throwIfNotFound: true);
        m_TetrisRight_Rotate = m_TetrisRight.FindAction("Rotate", throwIfNotFound: true);
        // TetrisLeft
        m_TetrisLeft = asset.FindActionMap("TetrisLeft", throwIfNotFound: true);
        m_TetrisLeft_Move = m_TetrisLeft.FindAction("Move", throwIfNotFound: true);
    }

    ~@TetrisControls()
    {
        UnityEngine.Debug.Assert(!m_TetrisRight.enabled, "This will cause a leak and performance issues, TetrisControls.TetrisRight.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TetrisLeft.enabled, "This will cause a leak and performance issues, TetrisControls.TetrisLeft.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TetrisRight
    private readonly InputActionMap m_TetrisRight;
    private List<ITetrisRightActions> m_TetrisRightActionsCallbackInterfaces = new List<ITetrisRightActions>();
    private readonly InputAction m_TetrisRight_Rotate;
    public struct TetrisRightActions
    {
        private @TetrisControls m_Wrapper;
        public TetrisRightActions(@TetrisControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Rotate => m_Wrapper.m_TetrisRight_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_TetrisRight; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TetrisRightActions set) { return set.Get(); }
        public void AddCallbacks(ITetrisRightActions instance)
        {
            if (instance == null || m_Wrapper.m_TetrisRightActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TetrisRightActionsCallbackInterfaces.Add(instance);
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
        }

        private void UnregisterCallbacks(ITetrisRightActions instance)
        {
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
        }

        public void RemoveCallbacks(ITetrisRightActions instance)
        {
            if (m_Wrapper.m_TetrisRightActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITetrisRightActions instance)
        {
            foreach (var item in m_Wrapper.m_TetrisRightActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TetrisRightActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TetrisRightActions @TetrisRight => new TetrisRightActions(this);

    // TetrisLeft
    private readonly InputActionMap m_TetrisLeft;
    private List<ITetrisLeftActions> m_TetrisLeftActionsCallbackInterfaces = new List<ITetrisLeftActions>();
    private readonly InputAction m_TetrisLeft_Move;
    public struct TetrisLeftActions
    {
        private @TetrisControls m_Wrapper;
        public TetrisLeftActions(@TetrisControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_TetrisLeft_Move;
        public InputActionMap Get() { return m_Wrapper.m_TetrisLeft; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TetrisLeftActions set) { return set.Get(); }
        public void AddCallbacks(ITetrisLeftActions instance)
        {
            if (instance == null || m_Wrapper.m_TetrisLeftActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TetrisLeftActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(ITetrisLeftActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(ITetrisLeftActions instance)
        {
            if (m_Wrapper.m_TetrisLeftActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITetrisLeftActions instance)
        {
            foreach (var item in m_Wrapper.m_TetrisLeftActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TetrisLeftActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TetrisLeftActions @TetrisLeft => new TetrisLeftActions(this);
    public interface ITetrisRightActions
    {
        void OnRotate(InputAction.CallbackContext context);
    }
    public interface ITetrisLeftActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
