---
title: Demon
---
classDiagram
	namespace ControllerGroup {
		class Controller {
			+ UnityEvent<GameObject> BanishTriggered
			+ UnityEvent<GameObject> JumpscareTriggered
			+ UnityEvent JumpscareFxCompleted
			+ UnityEvent BanishFxCompleted
			+ UnityEvent<bool> Illuminated
			- OnTriggerEnter(Collider)
			+ PositionForJumpscare(GameObject)
			- OnJumpscareFxCompleted()
			- OnBanishFxCompleted()
		}
		class PositionForJumpscare["Controller.PositionForJumpscare"] {<<EventListener>>}
		class OnBanishFxCompleted["Controller.OnBanishFxCompleted"] {<<EventListener>>}
		class BanishTriggered["Controller.BanishTriggered"] {<<UnityEvent>>}
		class JumpscareTriggered["Controller.JumpscareTriggered"] {<<UnityEvent>>}
		class JumpscareFxCompleted["Controller.JumpscareFxCompleted"] {<<UnityEvent>>}
		class BanishFxCompleted["Controller.BanishFxCompleted"] {<<UnityEvent>>}
		class Illuminated["Controller.Illuminated"] {<<UnityEvent>>}
	}

	Controller o--> PositionForJumpscare : Owns
	JumpscareTriggered --> PositionForJumpscare : Runs
	Controller o--> OnBanishFxCompleted : Owns
	BanishFxCompleted --> OnBanishFxCompleted : Runs

	Controller --> JumpscareTriggered : Invokes

	Controller o--> BanishTriggered : Owns
	Controller o--> JumpscareTriggered : Owns
	Controller o--> JumpscareFxCompleted : Owns
	Controller o--> BanishFxCompleted : Owns
	Controller o--> Illuminated : Owns
	
	class Health {
    	- Helpers.ClampedFloat _hp
    	- OnTriggerExit(Collider)
    	- OnTriggerStay(Collider)
    }
    
    Health --> Illuminated : Invokes
	Health --> BanishTriggered: Invokes

	namespace FxControllerGroup {
		class FxController {
	            - PlayJumpscareAudio()
	            + OnJumpscare(GameObject)
	            - AfterBanishFx()
	            - AfterJumpscareFx
        }
        class OnJumpscare["FxController.OnJumpscare"] {<<EventListener>>}
        class OnIlluminated["FxController.OnIlluminated"] {<<EventListener>>}
		class OnBanish["FxController.OnBanish"] {<<EventListener>>}
		class PlayJumpscareAudio["FxController.PlayJumpscareAudio"] {<<Function>>}
		class AfterBanishFx["FxController.AfterBanishFx"] {<<Function>>}
		class AfterJumpscareFx["FxController.AfterJumpscareFx"] {<<Function>>}

	}


	FxController o--> OnJumpscare : Owns
	FxController o--> OnIlluminated : Owns
	FxController o--> OnBanish : Owns
	FxController o--> PlayJumpscareAudio : Owns
	FxController o--> AfterBanishFx : Owns
	FxController o--> AfterJumpscareFx : Owns

	JumpscareTriggered --> OnJumpscare : Runs
	Illuminated --> OnIlluminated : Runs
	BanishTriggered --> OnBanish : Runs
	
	OnJumpscare --> Animator : SetTrigger(Jumpscare)
	OnBanish --> Animator : SetTrigger(Banish)
	OnIlluminated --> Animator : SetBool(Illuminated)
	
	namespace Animation {
		class Animator {
			+ Trigger Jumpscare
			+ Trigger Banish
			+ bool Illuminated
		}
		class Banish {<<AnimationClip>>}
		class Jumpscare {<<AnimationClip>>}
	}
	
	Animator o--> Banish : Owns
	Animator o--> Jumpscare : Owns
	
	Jumpscare --> PlayJumpscareAudio : Runs
    Jumpscare --> AfterJumpscareFx : Runs
    Banish --> AfterBanishFx : Runs
    
    AfterBanishFx --> BanishFxCompleted : Invokes
    AfterJumpscareFx --> JumpscareFxCompleted : Invokes
    

	
     